/*

 SRC1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 28 x 28
   Tile set      : D:\Sensei\Sensei1\JPText.gbr
   Plane count   : 4 planes (32 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define src1Width 28
#define src1Height 28
#define src1Bank 0

#define src1 src1PLN0
extern unsigned char src1PLN0[];
extern unsigned char src1PLN1[];
extern unsigned char src1PLN2[];
extern unsigned char src1PLN3[];

/* End of SRC1.H */
